# -*- coding: utf-8 -*-
"""KMeans Clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D5D3BVJfpfE831qo-PLWeHAqLq1Vnsxw

KMeans Clustering for Load_iris
"""

import pandas as pd
iris = pd.read_csv("irisexcel.csv")
x = iris[['sepal_length','sepal_width']]

from sklearn.cluster import KMeans
ML = KMeans(n_clusters=5, max_iter=4)
ML = ML.fit(x)

# centers & Labels
centers = ML.cluster_centers_
labels = ML.labels_
print (centers)
print (labels)

import matplotlib.pyplot as plt
xaxis = iris["sepal_length"]
yaxis = iris["sepal_width"]
plt.scatter(x=xaxis,y=yaxis,c=labels,cmap="rainbow")
plt.show()

"""KMeans for Make_blob"""

from sklearn.datasets import make_blobs
dataset = make_blobs(n_samples = 200, n_features = 6, centers = 4, cluster_std = 2, random_state=50)
points = dataset[0]

from sklearn.cluster import KMeans
k_means = KMeans(n_clusters=5, n_init=25)
k_means.fit(points)

#Centers and labels
centers = ML.cluster_centers_
labels = ML.labels_
print("Centers = ", centers)
print("Labels = ",labels)

#plot
import matplotlib.pyplot as plt
clusters = k_means.cluster_centers_
y = k_means.fit_predict(points)
plt.scatter(points[y == 0,0],points[y == 0,1],s =80, color = 'red')
plt.scatter(points[y == 1,0],points[y == 1,1],s =80, color = 'blue')
plt.scatter(points[y == 2,0],points[y == 2,1],s =80, color = 'yellow')
plt.scatter(points[y == 3,0],points[y == 3,1],s =80, color = 'green')
plt.scatter(points[y == 4,0],points[y == 4,1],s =80, color = 'black')
plt.show()

import pandas as pd
heart = pd.read_csv("/content/heart.csv")
x = heart[['trestbps','chol','thalach']]

from sklearn.cluster import KMeans
ML = KMeans(n_clusters=3, max_iter=10, n_init=10, random_state=20)
ML = ML.fit(x)

#Centers and labels
centers = ML.cluster_centers_
labels = ML.labels_
print("Centers = ", centers)
print("Labels = ",labels)

#plot
import matplotlib.pyplot as plt
axis = plt.axes(projection='3d')
xaxis = heart["trestbps"]
plt.xlabel("trestbps")
yaxis = heart["chol"]
plt.ylabel("Cholestrol")
zaxis = heart["thalach"]
plt.title("3D- KMeans Clustering (Heart Dataset)")
axis.scatter3D(xs=xaxis,ys=yaxis,zs=zaxis,c=labels,cmap="rainbow")